import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from 'styles/Home.module.css';
import { AppShell, Container } from '@mantine/core';
import { Header } from 'src/components/Header';
import { TitleSection } from 'src/components/TitleSection';
import { Footer } from 'src/components/Footer';
import { Navbar } from 'src/components/Navbar';
import { useResizeObserver } from '@mantine/hooks';
import { isMobileWidth } from 'src/utils/mobile';

const Home: NextPage = () => {
  const [opened, setOpened] = useState<boolean>(false);
  const [isMobileUi, setIsMobileUi] = useState<boolean>(true);
  const [ref, rect] = useResizeObserver();

  const toggleOpenState = (): void => setOpened((prev) => !prev);

  useEffect(() => {
    setIsMobileUi(isMobileWidth(rect.width));
  }, [rect.width]);

  return (
    <AppShell
      padding='md'
      header={
        <Header
          isMobileUi={isMobileUi}
          opened={opened}
          toggleOpenState={toggleOpenState}
        />
      }
      footer={<Footer />}
      navbarOffsetBreakpoint='sm'
      navbar={<Navbar isMobileUi={isMobileUi} opened={opened} />}
      ref={ref}
    >
      <Head>
        <title>Next Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container className={styles.container}>
        {' '}
        <TitleSection name='ピータン' />
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/canary/examples'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </Container>
    </AppShell>
  );
};

export default Home;
