import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {
  Anchor,
  AppShell,
  Burger,
  Container,
  Footer,
  Header,
  MediaQuery,
  Navbar,
} from '@mantine/core';

const Home: NextPage = () => {
  const [opened, setOpened] = useState(false);
  return (
    <Container>
      <AppShell
        padding='md'
        header={
          <Header height={70} p='md'>
            <div className={styles.header}>
              <MediaQuery largerThan='sm' styles={{ display: 'none' }}>
                <Burger
                  opened={opened}
                  onClick={() => setOpened((prev) => !prev)}
                  size='sm'
                  title='バーガーメニュー'
                  mr='xl'
                />
              </MediaQuery>
              <h1 className={styles.title}>Shimabu IT University</h1>
              <MediaQuery
                smallerThan='sm'
                styles={{ display: 'none' }}
                className={styles.menu}
              >
                <div>
                  <Anchor href='-' target='_self'>
                    About
                  </Anchor>
                  <Anchor href='-' target='_self'>
                    Blog
                  </Anchor>
                  <Anchor href='-' target='_self'>
                    Portfolio
                  </Anchor>
                  <Anchor href='-' target='_self'>
                    Contact
                  </Anchor>
                </div>
              </MediaQuery>
            </div>
          </Header>
        }
        footer={
          <Footer height={60} p='md' className={styles.footer}>
            <a
              href='https://www.youtube.com/c/shimabu_it/'
              target='_blank'
              rel='noopener noreferrer'
            >
              &copy; 2022 Shimabu IT University
            </a>
          </Footer>
        }
        navbarOffsetBreakpoint='sm'
        navbar={
          <MediaQuery largerThan='sm' styles={{ display: 'none' }}>
            <Navbar
              p='md'
              hiddenBreakpoint='sm'
              hidden={!opened}
              width={{ sm: 200, lg: 300 }}
              className={styles.navbar}
            >
              <Navbar.Section mt='md'>About</Navbar.Section>
              <Navbar.Section>Blog</Navbar.Section>
              <Navbar.Section>Portfolio</Navbar.Section>
              <Navbar.Section>Contact</Navbar.Section>
            </Navbar>
          </MediaQuery>
        }
      >
        <Head>
          <title>Next Portfolio</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            <a href='https://nextjs.org/docs' className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href='https://nextjs.org/learn' className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href='https://github.com/vercel/next.js/tree/canary/examples'
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>
      </AppShell>
    </Container>
  );
};

export default Home;
